### ISSUE TITLE
Error Pls Help

### ISSUE THREAD

**Issue by DevEZPhoenix** [Red-company/RDDoS_Tool#2]
⋊> ~/RDDoS_Tool on main ◦ python3 RDDoS_Tool.py                                              21:05:54
Traceback (most recent call last):
  File "/data/data/com.termux/files/home/RDDoS_Tool/RDDoS_Tool.py", line 15, in <module>
    import pyfiglet
  File "/data/data/com.termux/files/usr/lib/python3.11/site-packages/pyfiglet/__init__.py", line 8, in <module>
    import pkg_resources
ModuleNotFoundError: No module named 'pkg_resources'

**Comment by LycanOskari** [comment]
Same here

**Comment by kming2011** [comment]
# Input.
opt = str(input("\n> "))

# Selection.
if opt == '1':
    domain = str(input("Domain:"))
    ip = socket.gethostbyname(domain)
    break

elif opt == '2':
    ip = str(input("IP Address: "))
    break

elif opt == '3':
    print("\n\033[101mEasy.       .سهل\033[0m  \033[101m       \033[0m  \033[101m        \033[0m \033[101m       \033[0m \033[0m                \033[92m_____\033[0m")
    print("                  \033[101m   \033[0m  \033[101m   \033[0m \033[101m   \033[0m      \033[101m   \033[0m  \033[101m   \033[0m\033[0m             \033[92m.-'     '-.\033[0m")
    print("\033[101mOpen.      .افتح\033[0m  \033[101m       \033[0m  \033[101m      \033[0m   \033[101m   \033[0m  \033[101m   \033[0m           \033[92m.'\033[91m____\033[0m secure\033[92m'.\033[0m")
    print("                  \033[101m   \033[0m \033[101m   \033[0m  \033[101m   \033[0m      \033[101m   \033[0m  \033[101m   \033[0m          \033[92m/  \033[91m|  _ \\\033[0m  \033[93m__\033[0m   \033[92m\\\033[0m")
    print("\033[101mSecure.    .يؤمن\033[0m  \033[101m   \033[0m  \033[101m   \033[0m \033[101m        \033[0m \033[101m       \033[0m          \033[92m;\033[0m r \033[91m| |_) /\033[0m\033[93m/ o\\\033[0m t \033[92m;\033[0m")
    print("                                                     \033[92m|\033[0m e \033[91m|  _ <\033[0m \033[93m\\__/\033[0m e \033[92m|\033[0m")
    print("RedDDoS Tool is an open source tool for              \033[92m;\033[0m d \033[91m|_| \\ \\\033[0m \033[93m<|\033[0m  a \033[92m;\033[0m")
    print("penetration. You can test networks/servers/any        \033[92m\\       \033[91m\\/\033[0m \033[93m<|\033[0m  m\033[92m/\033[0m")
    print("other devices with it.                                 \033[92m'.\033[0m member \033[93m<|\033[0m \033[92m.'\033[0m")
    print("                                                         \033[92m'-._____.-'\033[0m")
    print("Author of the program is not responsible for")
    print("it's usage, everybody MUST use it ONLY in         member-id: 'rst-00000002'")
    print("legit cases.")
    print("\nFor more information visit project's site.")
    
    goon = input("\n\n\n\n\n\n\nPress Enter to continue.")
    os.system(cmd_clear)

elif opt == '4':
    exit()

else:
    print('\033[91mInvaild Choice!\033[0m')
    time.sleep(2)
    os.system(cmd_clear)
