### ISSUE TITLE
Error 

Traceback (most recent call last):
  File "/data/data/com.termux/files/home/RDDoS_Tool/RDDoS_Tool.py", line 15, in <module>
    import pyfiglet
  File "/data/data/com.termux/files/usr/lib/python3.11/site-packages/pyfiglet/__init__.py", line 8, in <module>
    import pkg_resources
ModuleNotFoundError: No module named 'pkg_resources' 

Thats what i get when starting the script. 

### ISSUE THREAD

**Issue by Damp3nxxx** [Red-company/RDDoS_Tool#3]

**Comment by b-danz** [comment]
Ok firstly... try..

Pip install setuptools
Or
Pip3 install setuptools

Then
Pip install --upgrade setuptools
Or
pip3 install --upgrade setuptools

Then try running the script over again.

It's either you don't have the tools setup or you need to restore the depreciated code back. This uses a old python.

Perhaps this should be updated or added into the setup code.
