### ISSUE TITLE
Traceback (most recent call last):   File "C:\Users\sabah\RDDoS_Tool\RDDoS_Tool\RDDoS_Tool.py", line 10, in <module>     from   tqdm.auto import tqdm ModuleNotFoundError: No module named 'tqdm'

### ISSUE THREAD

**Issue by Kingofthescript** [Red-company/RDDoS_Tool#7]
Traceback (most recent call last):
  File "C:\Users\sabah\RDDoS_Tool\RDDoS_Tool\RDDoS_Tool.py", line 10, in <module>
    from   tqdm.auto import tqdm
ModuleNotFoundError: No module named 'tqdm'

FIX PLEASE

**Comment by paodebatalha** [comment]
Bro, you just need install the module

**Comment by Kingofthescript** [comment]
mb mb

**Comment by UnknownH4D** [comment]
Yeah, I have that same problem, reinstalled, and installed tqdm, yet it still doesn't work.
